spring:
  jms:
    listener:
      acknowledge-mode: auto
    pub-sub-domain: false
  artemis:
    host: localhost
    user: capp
    password: admin
    mode: native
    port: 61616
    embedded:
      enabled: false
spike:
  event-publisher: ${event-publisher:false}
  customer-publisher: ${customer-publisher:false}
  event-consumer: ${event-consumer:false}
  customer-consumer: ${customer-consumer:false}
  queue-name:
    event-update: capp.topic.eventupdate
    customer-update: 222222